`drop_alternatives.py` is a simple Python script for those who hate emails in
HTML and who prefer their inbox to have as many messages in pure text as
feasible. Given an RFC-2822 message message, it generates its 'sanitized'
version.

This script is generally meant to be run as a filter with procmail,
https://github.com/nicm/fdm[FDM] or some other mail delivery agent.

It tries to be moderately conservative and only act when things are
moderately safe:

* drops the `text/html` parts that have a corresponding `text/plain` part ;
* in all other cases keep the message intact.

== Performance note
In a quest for performance, I compared Python 3 and Python 2 versions of the
code. Python 2.7 appeared to be 20% quicker than Python 3.4 in Debian
stable 8.9 for the 100 runs of the 24 _doctests_ (at 2017-10-21, see
`time_drop_alternatives.py` comments for more details). So I kept using Python
2 and made a cross-compatible version.

== `fdm.conf` example :
`match all action rewrite "python2 -SE drop_alternatives.py" continue`

== Tests
Around 20 _doctests_ are included. You can run them with the following command in
the cloned repository root: +
`python -m doctest drop_alternatives.py`

No output means a success.

== Author
* 2017: Simon Descarpentries
* 2010-2012: https://github.com/rbrito[rbrito] from a StackExchange https://codereview.stackexchange.com/questions/12967/script-to-drop-html-part-of-multipart-mixed-e-mails/12970[thread].

== Ressources
Github repository : https://github.com/Siltaar/drop_alternatives

== Licensing
GNU General Public License v3.0. See LICENCE file for more information.

