`drop_alternatives.py` is a simple Python script for those who hate emails in
HTML and who prefer their inbox to have as many messages in pure text as
feasible. Given an RFC-2822 message message, it generates its 'sanitized'
version.

This script is generally meant to be run as a filter with procmail,
https://github.com/nicm/fdm[FDM] or some other mail delivery agent.

It tries to be moderately conservative and only act when things are
moderately safe:

* drops the `text/html` parts that have a corresponding `text/plain` part ;
* in all other cases keep the message intact.

To find corresponding parts, 280 decoded and HTML-purged characters are
compared at the begining and the end of the parts, via the `quick_ratio()`
function of Python's SequenceMatcher. If one segment matches at 91% or more, or
if both matches at 81% or more, the parts are declared corresponding.

== Performance note
In a quest for performance, I compared Python 3 and Python 2 versions of the
code. Python 2.7 appeared to be 20% quicker than Python 3.4 in Debian
stable 8.9 for the 100 runs of the 24 _doctests_ (at 2017-10-21, see
`time_drop_alternatives.py` comments for more details).

Python 2.7.13 still appear to be 10% quicker than Python 3.5.3 in Debian stable
9.3 for 5 time 10 runs of 33 tests (at 2018-03-15).

So I kept using Python 2 and made a cross-compatible version.

== `fdm.conf` example :
`match all action rewrite "python2 -SE drop_alternatives.py" continue`

== Tests
Around 30 _doctests_ are included. You can run them with the following command in
the cloned repository root: +
`python -m doctest drop_alternatives.py`

Outputs HTML text to compare in bold (grey 1st, white others), bad marks in yellow and failed in red.
Best viewed with a 290 character wide capable console.

== Author
* 2017-路路路路: Simon Descarpentries
* 2010-2012: https://github.com/rbrito[rbrito] from a StackExchange https://codereview.stackexchange.com/questions/12967/script-to-drop-html-part-of-multipart-mixed-e-mails/12970[thread].

== Ressources
Github repository : https://github.com/Siltaar/drop_alternatives

== Licensing
GNU General Public License v3.0. See LICENCE file for more information.

