`drop_alternatives.py` is a simple Python script for those who wants to save
disk space removing HTML alternatives in their emails. Given an RFC-2822
message message, it generates its 'sanitized' version.

This script is generally meant to be run as a filter with procmail,
https://github.com/nicm/fdm[FDM] or other mail delivery agent.

It tries to be conservative and only acts when things are moderately safe:

* drops the non `text/plain` parts of a `message/alternative` with same text content ;
* in all other cases keep the message intact.

The script inserts a `x-drop-alt` custom email-header which logs the
content-types of the dropped parts.

== `fdm.conf` example :
`match all action rewrite "python3 -IOq drop_alternatives.py" continue`

== Tests
Around 30 _doctests_ are included. You can run them with the following command in
the cloned repository root: +
`./test_drop_alternatives.py`

No output is a success.

== Author
* 2017-2018: Simon Descarpentries, major rewrite in 2018-04
* 2010-2012: https://github.com/rbrito[rbrito] from a StackExchange https://codereview.stackexchange.com/questions/12967/script-to-drop-html-part-of-multipart-mixed-e-mails/12970[thread].

== Ressources
Github repository : https://github.com/Siltaar/drop_alternatives

== Licensing
GNU General Public License v3.0. See LICENCE file for more information.

